version: '3'

services:
  web:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile-local
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:8000:8000
    entrypoint: bash -c "./wait-for-it.sh postgres:5432 -- python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  bot:
    restart: unless-stopped
    build:
      context: ./docker/bot
      dockerfile: Dockerfile-local
    depends_on:
      - web

  postgres:
    image: postgres:12.4
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PG_DATABASE_NAME}
      - POSTGRES_USER=${PG_DATABASE_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 127.0.0.1:8080:8080
